.TH "comp_module_t" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comp_module_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <comp_module\&.h>\fP
.PP
Inherits \fBshell_module_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcomp_module_t\fP (\fBchar\fP *modules_coms, \fBlista\fP< \fBprot_module_t\fP * > &\fBprot_modules\fP)"
.br
.ti -1c
.RI "\fBcomp_module_t\fP (\fBsize_t\fP \fBbe_db\fP, \fBsize_t\fP \fBki_db\fP, \fBsize_t\fP m_db)"
.br
.ti -1c
.RI "\fBmodule_t\fP * \fBcopy\fP () \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_ki_port\fP (\fBsize_t\fP \fBki_index\fP, \fBmodule_t\fP *modulep, \fBsize_t\fP \fBbe_index\fP)"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBget_ki_ertek\fP (\fBsize_t\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBsize_t\fP \fBget_ki_num\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_connection\fP (\fBchar\fP \fBc\fP, \fBmodule_t\fP *&\fBbase\fP, \fBsize_t\fP \fBki_index\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcomp_create_modules\fP (\fBbool\fP \fBcopy\fP, \fBlista\fP< \fBsize_t\fP > &\fBvegk\fP, \fBlista\fP< \fBsize_t\fP > &\fBkezk\fP, \fBlista\fP< \fBprot_module_t\fP * > *\fBprot_modules\fP, \fBmodule_t\fP **&\fBmodules_ref\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcomp_fill_module\fP (\fBlista\fP< \fBsize_t\fP > &\fBvegk\fP)"
.br
.ti -1c
.RI "\fB~comp_module_t\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBshell_module_t\fP
.in +1c
.ti -1c
.RI "\fBshell_module_t\fP (\fBsize_t\fP ports=0)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinit\fP (\fBsize_t\fP ports)"
.br
.ti -1c
.RI "\fBmodule_t\fP * \fBcopy\fP () \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_to_list\fP (\fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP, \fBsize_t\fP \fBbe\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_be\fP (\fBsize_t\fP \fBindex\fP, \fBuint8_t\fP ertek) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~shell_module_t\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBmodule_t\fP
.in +1c
.ti -1c
.RI "\fBmodule_t\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBvegrehajtas\fP (\fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP)"
.br
.ti -1c
.RI "\fBsize_t\fP \fBget_be_num\fP ()"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBget_be_ertek\fP (\fBsize_t\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~module_t\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBmodule_t\fP
.in +1c
.ti -1c
.RI "\fBsize_t\fP \fBbe_db\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBki_db\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbe_ertek\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBki_ertek\fP"
.br
.ti -1c
.RI "\fBlista\fP< \fBport\fP< \fBmodule_t\fP * > > * \fBki_ports\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "comp_module_t::comp_module_t (\fBchar\fP * modules_coms, \fBlista\fP< \fBprot_module_t\fP * > & prot_modules)"
Constructor for the \fBcomp_module_t\fP class\&.
.PP
\fBParameters\fP
.RS 4
\fImodules_coms\fP the character array containing module command 
.br
\fIprot_modules\fP list of modules prototypes 
.RE
.PP

.SS "comp_module_t::comp_module_t (\fBsize_t\fP be_dab, \fBsize_t\fP ki_dab, \fBsize_t\fP m_dab)"
Constructor for \fBcomp_module_t\fP class\&.
.PP
\fBParameters\fP
.RS 4
\fIbe_db\fP number of inputs 
.br
\fIki_db\fP number of outputs 
.br
\fIm_db\fP number of the modules 
.br
\fIw_db\fP number of wires 
.RE
.PP

.SS "comp_module_t::~comp_module_t ()"
Destructor for the \fBcomp_module_t\fP class, responsible for cleaning up memory and resources\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP comp_module_t::comp_create_modules (\fBbool\fP copy, \fBlista\fP< \fBsize_t\fP > & vegk, \fBlista\fP< \fBsize_t\fP > & kezk, \fBlista\fP< \fBprot_module_t\fP * > * prot_modules, \fBmodule_t\fP **& modules_ref)"
Fills modules based on previous calculations\&.
.PP
\fBParameters\fP
.RS 4
\fIcopy\fP if for coping modules 
.br
\fIm_db\fP number of the modules 
.br
\fIbe_db\fP number of inputs 
.br
\fIki_db\fP number of outputs 
.br
\fIw_db\fP number of wires 
.br
\fImodules_coms\fP the character array containing module command 
.br
\fIvegk\fP the list of the starter indexes 
.br
\fIkezk\fP the list of the end indexes 
.br
\fImodules\fP array of modules 
.br
\fIend_module\fP the end module 
.br
\fIki_wires\fP output wires(inputs) 
.br
\fIwires\fP inner wires 
.br
\fIprot_modules\fP list of modules prototypes 
.br
\fImodules_ref\fP reference to modules 
.RE
.PP

.SS "\fBvoid\fP comp_module_t::comp_fill_module (\fBlista\fP< \fBsize_t\fP > & vegk)"

.SS "\fBmodule_t\fP * comp_module_t::copy ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBmodule_t\fP\&.
.SS "\fBuint8_t\fP comp_module_t::get_ki_ertek (\fBsize_t\fP i)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBmodule_t\fP\&.
.SS "\fBsize_t\fP comp_module_t::get_ki_num ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBmodule_t\fP\&.
.SS "\fBvoid\fP comp_module_t::set_connection (\fBchar\fP c, \fBmodule_t\fP *& base, \fBsize_t\fP ki_index)"

.SS "\fBvoid\fP comp_module_t::set_ki_port (\fBsize_t\fP ki_index, \fBmodule_t\fP * modulep, \fBsize_t\fP be_index)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBmodule_t\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
