.TH "comp_module.h" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comp_module.h
.SH SYNOPSIS
.br
.PP
\fR#include 'shell_module\&.h'\fP
.br
\fR#include 'prot_modules\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcomp_module_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
