.TH "karakter_keszlet.h" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
karakter_keszlet.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBbool\fP \fBkk\fP [256]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBconst\fP \fBbool\fP kk[256]"

.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
