.TH "module.h" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
module.h
.SH SYNOPSIS
.br
.PP
\fR#include 'ossz\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBport< T >\fP"
.br
.ti -1c
.RI "class \fBmodule_t\fP"
.br
.ti -1c
.RI "struct \fBport< module_t * >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
