.TH "module_t" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
module_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <module\&.h>\fP
.PP
Inherited by \fBshell_module_t\fP, and \fBtext_module_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmodule_t\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBmodule_t\fP * \fBcopy\fP ()=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBvegrehajtas\fP (\fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_to_list\fP (\fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP, \fBsize_t\fP \fBbe\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_be\fP (\fBsize_t\fP \fBindex\fP, \fBuint8_t\fP ertek)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_ki_port\fP (\fBsize_t\fP \fBki_index\fP, \fBmodule_t\fP *modulep, \fBsize_t\fP \fBbe_index\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsize_t\fP \fBget_ki_num\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBuint8_t\fP \fBget_ki_ertek\fP (\fBsize_t\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBsize_t\fP \fBget_be_num\fP ()"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBget_be_ertek\fP (\fBsize_t\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~module_t\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsize_t\fP \fBbe_db\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBki_db\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbe_ertek\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBki_ertek\fP"
.br
.ti -1c
.RI "\fBlista\fP< \fBport\fP< \fBmodule_t\fP * > > * \fBki_ports\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "module_t::module_t ()\fR [inline]\fP"

.SS "module_t::~module_t ()\fR [virtual]\fP"
Destructor for the \fBmodule_t\fP class\&. Deletes all the output wires in the module\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP module_t::add_to_list (\fBlista\fP< \fBmodule_t\fP * > & wait_for_do, \fBsize_t\fP be)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBshell_module_t\fP\&.
.SS "\fBvirtual\fP \fBmodule_t\fP * module_t::copy ()\fR [pure virtual]\fP"

.PP
Implemented in \fBcomp_module_t\fP, \fBshell_module_t\fP, and \fBtext_module_t\fP\&.
.SS "\fBuint8_t\fP module_t::get_be_ertek (\fBsize_t\fP i)\fR [inline]\fP"

.SS "\fBsize_t\fP module_t::get_be_num ()\fR [inline]\fP"

.SS "\fBvirtual\fP \fBuint8_t\fP module_t::get_ki_ertek (\fBsize_t\fP i)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBcomp_module_t\fP\&.
.SS "\fBvirtual\fP \fBsize_t\fP module_t::get_ki_num ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBcomp_module_t\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP module_t::set_be (\fBsize_t\fP index, \fBuint8_t\fP ertek)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBshell_module_t\fP\&.
.SS "\fBvoid\fP module_t::set_ki_port (\fBsize_t\fP ki_index, \fBmodule_t\fP * modulep, \fBsize_t\fP be_index)\fR [virtual]\fP"

.PP
Reimplemented in \fBcomp_module_t\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP module_t::vegrehajtas (\fBlista\fP< \fBmodule_t\fP * > & wait_for_do)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBtext_module_t\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsize_t\fP module_t::be_db\fR [protected]\fP"

.SS "\fBuint8_t\fP* module_t::be_ertek\fR [protected]\fP"

.SS "\fBsize_t\fP module_t::ki_db\fR [protected]\fP"

.SS "\fBuint8_t\fP* module_t::ki_ertek\fR [protected]\fP"

.SS "\fBlista\fP<\fBport\fP<\fBmodule_t\fP*> >* module_t::ki_ports\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
