.TH "ossz.h" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ossz.h
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include 'memtrace\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlista< T >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBlow\fP   '0'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBhigh\fP   '1'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBundet\fP   '?'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBeggyezik\fP (\fBconst\fP \fBchar\fP *\fBstr\fP, \fBconst\fP \fBchar\fP *\fBstr2\fP, \fBsize_t\fP \fBkez\fP, \fBsize_t\fP \fBveg\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP high   '1'"

.SS "#\fBdefine\fP low   '0'"

.SS "#\fBdefine\fP undet   '?'"

.SH "Function Documentation"
.PP 
.SS "\fBbool\fP eggyezik (\fBconst\fP \fBchar\fP * str, \fBconst\fP \fBchar\fP * str2, \fBsize_t\fP kez, \fBsize_t\fP veg)"
Checks if a substring of str matches str2 within the specified range\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP pointer to the string to be checked 
.br
\fIstr2\fP pointer to the string to compare against 
.br
\fIkez\fP starting index of the substring to compare 
.br
\fIveg\fP ending index of the substring to compare (exclusive)
.RE
.PP
\fBReturns\fP
.RS 4
true if the substring matches, false otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
