.TH "port< T >" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <module\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBmodulep\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBportszam\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBport\fP< \fBT\fP >::modulep"

.SS "template<\fBtypename\fP \fBT\fP > \fBsize_t\fP \fBport\fP< \fBT\fP >::portszam"


.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
