.TH "port< module_t * >" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
port< module_t * >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <module\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodule_t\fP * \fBmodulep\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBportszam\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmodule_t\fP* \fBport\fP< \fBmodule_t\fP * >::modulep"

.SS "\fBsize_t\fP \fBport\fP< \fBmodule_t\fP * >::portszam"


.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
