.TH "text_module_t" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
text_module_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <text_module\&.h>\fP
.PP
Inherits \fBmodule_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtext_module_t\fP (\fBconst\fP \fBchar\fP *parancsok)"
.br
.ti -1c
.RI "\fBtext_module_t\fP (\fBconst\fP \fBtext_module_t\fP &\fBrefe\fP)"
.br
.ti -1c
.RI "\fBmodule_t\fP * \fBcopy\fP () \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBvegrehajtas\fP (\fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_ki\fP (\fBsize_t\fP \fBindex\fP, \fBuint8_t\fP ertek, \fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP)"
.br
.ti -1c
.RI "\fB~text_module_t\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBmodule_t\fP
.in +1c
.ti -1c
.RI "\fBmodule_t\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_to_list\fP (\fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP, \fBsize_t\fP \fBbe\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_be\fP (\fBsize_t\fP \fBindex\fP, \fBuint8_t\fP ertek)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_ki_port\fP (\fBsize_t\fP \fBki_index\fP, \fBmodule_t\fP *modulep, \fBsize_t\fP \fBbe_index\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsize_t\fP \fBget_ki_num\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBuint8_t\fP \fBget_ki_ertek\fP (\fBsize_t\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBsize_t\fP \fBget_be_num\fP ()"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBget_be_ertek\fP (\fBsize_t\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~module_t\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBmodule_t\fP
.in +1c
.ti -1c
.RI "\fBsize_t\fP \fBbe_db\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBki_db\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbe_ertek\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBki_ertek\fP"
.br
.ti -1c
.RI "\fBlista\fP< \fBport\fP< \fBmodule_t\fP * > > * \fBki_ports\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "text_module_t::text_module_t (\fBconst\fP \fBchar\fP * parancsok)"
Constructor for \fBtext_module_t\fP class that initializes the variables based on the input command string\&.
.PP
\fBParameters\fP
.RS 4
\fIparancsok\fP The command string used to initialize the \fBtext_module_t\fP object 
.RE
.PP

.SS "text_module_t::text_module_t (\fBconst\fP \fBtext_module_t\fP & refe)"

.SS "text_module_t::~text_module_t ()"
Destructor for the \fBtext_module_t\fP class\&. Deletes the dynamically allocated memory\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBmodule_t\fP * text_module_t::copy ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBmodule_t\fP\&.
.SS "\fBvoid\fP text_module_t::set_ki (\fBsize_t\fP index, \fBuint8_t\fP ertek, \fBlista\fP< \fBmodule_t\fP * > & wait_for_do)"

.SS "\fBvoid\fP text_module_t::vegrehajtas (\fBlista\fP< \fBmodule_t\fP * > & wait_for_do)\fR [override]\fP, \fR [virtual]\fP"
Executes the logic for vegrehajtas\&.
.PP
\fBParameters\fP
.RS 4
\fIwait_for_do\fP list of \fBwire_t\fP pointers to wires, waiting to be processed 
.RE
.PP

.PP
Reimplemented from \fBmodule_t\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
