.TH "wire_t" 3 "nharamkkor_vs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wire_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wire\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwire_t\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd\fP (\fBport_t\fP *\fBnewport\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd\fP (\fBmodule_t\fP *modulep, \fBsize_t\fP idx)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBuint8_t\fP ertek)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetin\fP ()"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBget\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdoit\fP (\fBlista\fP< \fBmodule_t\fP * > &\fBwait_for_do\fP)"
.br
.ti -1c
.RI "\fB~wire_t\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "wire_t::wire_t ()"
Constructor for the \fBwire_t\fP class\&. 
.SS "wire_t::~wire_t ()"
Destructor for the \fBwire_t\fP class, delete all the ports\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP wire_t::add (\fBmodule_t\fP * modulep, \fBsize_t\fP idx)"
Adds a new port to the wire with the given module pointer and index\&.
.PP
\fBParameters\fP
.RS 4
\fImodulep\fP pointer to the module to add 
.br
\fIidx\fP index of the port to add 
.RE
.PP

.SS "\fBvoid\fP wire_t::add (\fBport_t\fP * newport)"
Adds a new port to the wire\&.
.PP
\fBParameters\fP
.RS 4
\fInewport\fP pointer to the port to be added 
.RE
.PP

.SS "\fBvoid\fP wire_t::doit (\fBlista\fP< \fBmodule_t\fP * > & wait_for_do)"
A function that adds the modules of ports to a list of modules after setting inputs\&.
.PP
\fBParameters\fP
.RS 4
\fIwait_for_do\fP list of \fBmodule_t\fP pointers to modules, waiting to be processed 
.RE
.PP

.SS "\fBuint8_t\fP wire_t::get ()"
Return the value of ertek\&. 
.SS "\fBvoid\fP wire_t::set (\fBuint8_t\fP ertek)"
Set the value of ertek\&.
.PP
\fBParameters\fP
.RS 4
\fIertek\fP The new value to set 
.RE
.PP

.SS "\fBvoid\fP wire_t::setin ()"
Set the input of all the ports\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for nharamkkor_vs from the source code\&.
