comp_module_t
shell_module_t comp_module_t::end_module
module_t** comp_module_t::modules
size_t comp_module_t::m_db
char* comp_module_t::modules_coms
comp_module_t::comp_module_t(char *modules_coms, lista< prot_module_t * > &prot_modules)
Constructor for the comp_module_t class. modules_coms the character array containing module command prot_modules list of modules prototypes
References module_t::be_db, module_t::be_ertek, comp_create_modules, comp_fill_module, shell_module_t::init, module_t::ki_db, module_t::ki_ertek, module_t::ki_ports, muvcount.
Referenced by copy.
comp_module_t::comp_module_t(size_t be_db, size_t ki_db, size_t m_db)
Constructor for comp_module_t class. be_db number of inputs ki_db number of outputs m_db number of the modules w_db number of wires
References module_t::be_db, module_t::be_ertek, shell_module_t::init, module_t::ki_db, module_t::ki_ertek, module_t::ki_ports.
module_t * comp_module_t::copy() override
References module_t::be_db, comp_create_modules, comp_fill_module, comp_module_t, get_ki_num, muvcount.
Referenced by comp_create_modules.
void comp_module_t::set_ki_port(size_t ki_index, module_t *modulep, size_t be_index)
References module_t::set_ki_port.
uint8_t comp_module_t::get_ki_ertek(size_t i)
References module_t::get_ki_ertek.
size_t comp_module_t::get_ki_num()
References module_t::get_ki_num.
Referenced by copy.
void comp_module_t::set_connection(char c, module_t *&base, size_t ki_index)
References module_t::set_ki_port.
Referenced by comp_fill_module.
void comp_module_t::comp_create_modules(bool copy, lista< size_t > &vegk, lista< size_t > &kezk, lista< prot_module_t * > *prot_modules, module_t **&modules_ref)
Fills modules based on previous calculations. copy if for coping modules m_db number of the modules be_db number of inputs ki_db number of outputs w_db number of wires modules_coms the character array containing module command vegk the list of the starter indexes kezk the list of the end indexes modules array of modules end_module the end module ki_wires output wires(inputs) wires inner wires prot_modules list of modules prototypes modules_ref reference to modules
References copy, module_t::copy, eggyezik.
Referenced by comp_module_t, copy.
void comp_module_t::comp_fill_module(lista< size_t > &vegk)
References lista< T >::add, module_t::be_db, module_t::ki_ports, module_t::set_be, set_connection, module_t::set_ki_port.
Referenced by comp_module_t, copy.
comp_module_t::~comp_module_t()
Destructor for the comp_module_t class, responsible for cleaning up memory and resources.