shell_module_t
shell_module_t::shell_module_t(size_t ports=0)
Constructor for shell_module_t class. ports the number of ports to initialize
References module_t::be_db, module_t::be_ertek, module_t::ki_db, module_t::ki_ertek, module_t::ki_ports.
Referenced by copy.
void shell_module_t::init(size_t ports)
Initializes the shell module with the given number of ports. ports the number of ports to initialize
References module_t::be_db, module_t::be_ertek, module_t::ki_db, module_t::ki_ertek, module_t::ki_ports.
Referenced by comp_module_t::comp_module_t, comp_module_t::comp_module_t.
module_t * shell_module_t::copy() override
References module_t::be_db, shell_module_t.
void shell_module_t::add_to_list(lista< module_t * > &wait_for_do, size_t be) override
References module_t::ki_ports, lista< T >::length.
void shell_module_t::set_be(size_t index, uint8_t ertek) override
Sets the value at the specified index in the inputs. index the index at which to set the value ertek the value to set
References module_t::ki_db, module_t::ki_ertek, module_t::ki_ports, lista< T >::length.
shell_module_t::~shell_module_t()
Destructor for the shell_module_t class.