lista
T lista< T >::elem
lista* lista< T >::next
T * lista< T >::getin(size_t i)
Retrieve the element at index i in the lista. i the index of the element to retrieve a pointer to the element at index i
lista< T >::lista()
Referenced by lista< T >::add, lista< T >::add, lista< T >::add, input_handler, input_handler_module, input_handler_read, input_handler_write, main, print, print_module_error, lista< T >::rem.
T & lista< T >::operator[](size_t i)
Retrieve the element at index i in the lista. i the index of the element to retrieve a reference to the element at index i
void lista< T >::add(T ertek)
Add a new element to the linked list. ertek the value to be added to the list
Referenced by lista< T >::add, lista< T >::add, lista< T >::add, wire_t::add, wire_t::add, lista< T >::add, lista< T >::add, module_t::add_to_list, comp_module_t::comp_fill_module, wire_t::doit, input_handler, input_handler_do, muv_list, muvcount, module_t::set_ki_port, test_module.
void lista< T >::add(lista< T > &addlist)
Adds the elements from the given list to the current list. addlist the list to be added
References lista< T >::add, lista< T >::length.
size_t lista< T >::length()
Calculates the length of the lista. The length of the lista.
References lista< T >::length.
Referenced by lista< T >::add, lista< T >::add, shell_module_t::add_to_list, wire_t::doit, input_handler_do, input_handler_module, input_handler_write, lista< T >::length, lepteto, modulesteszt, lista< T >::operator[], lista< T >::rem, shell_module_t::set_be, text_module_t::set_ki, wire_t::setin, ujmnev_ell, vegrehajt.
void lista< T >::rem(size_t i)
Removes an element at the specified index in the lista object. i the index of the element to be removed
References lista< T >::length, lista< T >::lista, lista< T >::rem.
Referenced by input_handler_do, lista< T >::rem.
void lista< T >::din()
A function that recursively deletes inner elements.
References lista< T >::din.
Referenced by lista< T >::din, main, wire_t::~wire_t.
void lista< T >::dinl()
A function that recursively deletes inner lists.
References lista< T >::dinl.
Referenced by lista< T >::dinl, main.
lista< T >::~lista()
size_t lista< size_t >::length()
References lista< T >::length.
size_t & lista< size_t >::operator[](size_t i)
References lista< T >::length.
void lista< size_t >::add(size_t ertek)
References lista< T >::add, lista< T >::lista.
void lista< size_t >::rem(size_t i)
References lista< T >::length, lista< T >::lista, lista< T >::rem.
void lista< module_t * >::add(lista< module_t * > &addlist)
References lista< T >::add, lista< T >::length.
void lista< module_t * >::rem(size_t i)
References lista< T >::length, lista< T >::lista, lista< T >::rem.
void lista< module_t * >::din()
References lista< T >::din.
size_t lista< prot_module_t * >::length()
References lista< T >::length.
prot_module_t *& lista< prot_module_t * >::operator[](size_t i)
References lista< T >::length.
void lista< prot_module_t * >::add(prot_module_t *ertek)
References lista< T >::add, lista< T >::lista.
void lista< prot_module_t * >::din()
References lista< T >::din.
void lista< char * >::add(char *ertek)
References lista< T >::add, lista< T >::lista.
size_t lista< char * >::length()
References lista< T >::length.
char *& lista< char * >::operator[](size_t i)
References lista< T >::length.
void lista< char * >::dinl()
References lista< T >::dinl.