comp_module.cpp
bool eggyezik(const char *str, const char *str2, size_t kez, size_t veg)
Checks if a substring of str matches str2 within the specified range. str pointer to the string to be checked str2 pointer to the string to compare against kez starting index of the substring to compare veg ending index of the substring to compare (exclusive) true if the substring matches, false otherwise
Referenced by comp_module_t::comp_create_modules, modulesteszt.
void muvcount(char *modules_coms, lista< size_t > &vegk, lista< size_t > &kezk, size_t &m_db, size_t &be_db, size_t &ki_db)
Calculates various counts and values based on the input string. modules_coms the character array containing module command vegk the list of the starter indexes kezk the list of the end indexes m_db the calculated number of modules based on characters in modules_coms be_db the calculated number of inputs based on characters in modules_coms ki_db the calculated number of outputs based on characters in modules_coms w_db the calculated number of wires based on characters in modules_coms
References lista< T >::add.
Referenced by comp_module_t::comp_module_t, comp_module_t::copy.