nharamkor_vs.cpp
bool ismod(char c)
Check if the character is a special symbol. c the character to be checked true if the character is '', '-', '+', or '!', false otherwise
Referenced by instruct_handler_char_handler.
void modulator(uint8_t c, uint8_t &mods)
Modifies the given mods variable based on the input character. c the character input to determine the modification mods the variable to be modified based on the input character
Referenced by instruct_handler_char_handler.
uint8_t ujmnev_ell(const char *nev, lista< prot_module_t * > &modules)
Check if the given name meets certain criteria and is not already in use. nev The name to be checked modules A list of modules to compare the name against 0 if the name is valid and not in use, 1 if the name not starts with '_', 2 if the name contains invalid characters, 3 if the name is already in use
References kk, lista< T >::length.
Referenced by test_module.
uint8_t kisbetujo(const char *str)
Checks if the input string contains at least one of each lowercase letter up to the "biggest" letter in use. And not contains syntactic error. str pointer to the input string 2 if wrong format, 1 if wrong character usage, 0 if it's valid
Referenced by test_module.
uint8_t kisbetujo2(const char *str)
Checks if the input string contains at least one of each lowercase letter up to the "biggest" letter in use and after a specific character every letter used as output. str pointer to the input string 1 if a letter used as an output more than once, 2 if it's not valid, 0 if it's valid
Referenced by test_module.
uint8_t nagybetujo(const char *str)
A function that checks the wiring connections of uppercase letters in the input string. str a pointer to the input string to be checked 0 if the wiring connections are correct, 1 if a letter used as an output more than once, 2 if there are incorrect wiring connections
Referenced by test_module.
uint8_t modulesteszt(const char *str, lista< prot_module_t * > &modules)
Function to check and validate modules based on input string. str The input string to check against modules. modules A list of modules to compare against the input string. 0 if successful, 1 if module does not exist, 2 if wrong input number, 3 if wrong output number.
References eggyezik, lista< T >::length.
Referenced by test_module.
uint8_t test_module(const char *str, lista< prot_module_t * > &modulok, bool add=true)
Function to test a module with the given name and commands. str the name and commands of the module to be tested modulok a list of module pointers to be tested against add flag to indicate whether to add the module 0 if successful, error code otherwise
References lista< T >::add, kisbetujo, kisbetujo2, modulesteszt, nagybetujo, ujmnev_ell.
Referenced by input_handler_module.
bool instruct_handler_char_handler(uint8_t *inputs, uint8_t c, T &state, uint8_t &mods, size_t &number)
A template function to handle different types of input characters and modify state accordingly. inputs pointer to an array of uint8_t to store inputs c the input character to handle state a reference to a template type T representing the current state mods a reference to a uint8_t to store modifiers number a reference to a size_t to store a number true if the input character is processed successfully, false otherwise
References ismod, modulator.
Referenced by instruct_handler.
bool instruct_handler(char *s, module_t *&m_main, uint8_t &mods, size_t &number, lista< module_t * > &wait_to_do_modules)
A function to handle instructions. s the instruction string w_inputs an array of wire_t inputs wait_to_do_wires a list of wire_t pointers to wires, waiting to be processed mods a uint8_t representing modifications number a size_t representing a number true if the function execution is successful, false otherwise
References instruct_handler_char_handler.
Referenced by input_handler_do.
char * getstring(std::istream &in, size_t h=0)
Recursively reads characters from the input stream and stores them in a dynamically allocated char array. in the input stream to read from h the current size of the char array being built a dynamically allocated char array containing the characters read from the input stream
References getstring.
Referenced by getstring, input_handler.
bool print_module_error(uint8_t err)
A function that prints error messages based on the error code passed in. err the error code to determine which error message to print true if error code is 0, false otherwise
References lista< T >::lista.
Referenced by input_handler_module.
void print(module_t *&m_main, bool kezd=true, bool lezar=true)
Prints the contents of the module to the console in a formatted manner. m_main a pointer to the module to be printed kezd flag indicating whether to include the beginning formatting lezar flag indicating whether to include the ending formatting
References lista< T >::lista.
Referenced by input_handler_do.
void input_handler(std::istream &in, lista< module_t * > &wait_to_do_modules, uint8_t &mods, lista< prot_module_t * > &modulok, module_t *&m_main, lista< char * > &insts)
Handles input from the given input stream and performs various operations based on the input. in the input stream to read from w_inputs array of wire inputs wait_to_do_wires list of wire_t pointers to wires, waiting to be processed mods uint8_t representing modifications modulok list of prot_module_t pointers representing modules m_main pointer to the main module insts list of instructions
References lista< T >::add, getstring, input_handler_do, input_handler_module, input_handler_read, input_handler_write, lista< T >::lista.
Referenced by input_handler_read, main.
void input_handler_module(char *s, lista< prot_module_t * > &modulok, module_t *&m_main)
Handles input for new module and sets the main module if the module is "_main". s input string w_inputs array of wire inputs modulok list of modules m_main pointer to the main module
References lista< T >::length, lista< T >::lista, print_module_error, test_module.
Referenced by input_handler.
void input_handler_read(char *s, lista< module_t * > &wait_to_do_wires, uint8_t &mods, lista< prot_module_t * > &modulok, module_t *&m_main, lista< char * > &insts)
A function to handle reading file, processing it. s the input file name w_inputs array of wire inputs wait_to_do_wires list of wire_t pointers to wires, waiting to be processed mods a uint8_t representing modifications modulok list of modules m_main pointer to the main module insts list of instructions
References input_handler, lista< T >::lista.
Referenced by input_handler.
void input_handler_write(char *s, lista< char * > &insts)
A function to handle writing instructions to file if the user wants. s the output file name insts list of instructions
References lista< T >::length, lista< T >::lista.
Referenced by input_handler.
bool input_handler_do(char *s, lista< module_t * > &wait_to_do_modules, uint8_t &mods, module_t *&m_main)
A function that handles input based on the given parameters. s the input character array w_inputs array of wire inputs wait_to_do_wires list of wire_t pointers to wires, waiting to be processed mods a uint8_t representing modifications m_main pointer to the main module true if input handling is successful, false otherwise
References lista< T >::add, instruct_handler, lista< T >::length, print, lista< T >::rem.
Referenced by input_handler.
int main()
Main function... That's all.
References lista< T >::din, lista< T >::dinl, input_handler, lista< T >::lista.