text_module.cpp
uint8_t mynot(uint8_t a)
A function that performs a NOT operation on the inputs. a The input value to perform the NOT operation on. The result of the NOT operation.
References high, low, undet.
Referenced by muvs, vegrehajt.
uint8_t myand(uint8_t a, uint8_t b)
Calculates the AND operation between two input values. a the first input b the second input the result of the AND operation between the two inputs
References high, low, undet.
Referenced by muvs.
uint8_t myor(uint8_t a, uint8_t b)
Calculates the OR operation between two input values. a the first input b the second input the result of the OR operation between the two inputs
References high, low, undet.
Referenced by muvs.
uint8_t myxor(uint8_t a, uint8_t b)
Calculates the XOR operation between two input values. a the first input b the second input the result of the XOR operation between the two inputs
References high, low, undet.
Referenced by muvs.
void lepteto(size_t torlendo, size_t index, lista< size_t > &hely, char *&ideiglenes, size_t &hossz)
Remove a specified number of elements from the given index in the list and update the list accordingly. torlendo the number of elements to remove index the index from which to start removal hely the list containing the indices ideiglenes the temporary character array hossz the length of the character array
References lista< T >::length.
Referenced by muvs, vegrehajt.
bool muvs(size_t index, lista< size_t > &hely, char *&ideiglenes, size_t &hossz, bool neg, uint8_t &ertek, size_t &iertek)
Function for performing a specific operation based on the input parameters. index The index parameter for the operation hely the list containing the indices ideiglenes the temporary character array hossz the length of the character array neg Boolean value indicating negation ertek the return value iertek the index of the return value to be placed True if the task is successfully performed, false otherwise
References lepteto, myand, mynot, myor, myxor.
Referenced by vegrehajt.
void muv_list(char &c, char &cn, size_t &index, lista< size_t > &hely, lista< size_t > &fsag, size_t &moz, size_t &fs, size_t &maxfsag, uint8_t *&be_ertek)
Updates the muv list based on the given character. c the current character cn the next character index the index hely the list of locations fsag the list of priorities moz the number of moves fs the current priority value maxfsag the maximum priority value in the list be_ertek the input values
References lista< T >::add.
Referenced by text_module_t::vegrehajtas.
void vegrehajt(size_t &maxfsag, lista< size_t > &hely, lista< size_t > &fsag, char *&ideiglenes, size_t &hossz)
Executes a series of operations on the input parameters to modify the ideiglenes array and the hely list. maxfsag the maximum priority value in the list hely the list of locations fsag the list of priorities ideiglenes the character array to be modified hossz the length of ideiglenes
References lista< T >::length, lepteto, muvs, mynot.
Referenced by text_module_t::vegrehajtas.